name: CI

env:
  CI: false

on:
  push:
    branches: [master]

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: build
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install pnpm -g
      - run: pnpm install
      - run: pnpm build:homepage

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: website/build
